generatorName: typescript-fetch
inputSpec: /local/openapi/openapi.yaml
output: /local/src/generated/openapi-client
additionalProperties:
  supportsES6: true
  useSingleRequestParameter: true
  withInterfaces: true
  enumPropertyNaming: original
  typescriptThreePlus: true
  useUnionTypes: true
  modelPropertyNaming: original
  npmName: '@office-manager/api-client'
  npmVersion: '0.1.0'
  npmRepository: 'https://registry.npmjs.org'
  withSeparateModelsAndApi: true
typeMappings:
  Date: string
